apiVersion: v1
kind: Service
metadata:
  name: dante-proxy-svc
  namespace: default
spec:
  selector:
    app: dante-proxy
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 1080
      targetPort: 1080