name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Jalankan setiap ada push ke branch `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Kirim Notifikasi via API
      - name: Send Notification
        env:
          API_URL: https://wa-api.nyuuk.my.id/api/send-message
          API_SECRET: ${{ secrets.API_SECRET }}
          API_KEY: HELLOWORLD
          NUMBER_NOTIFICATION: 6285156803524
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          LAST_COMMIT=$(git log -1 --pretty=format:"%s")
          AUTHOR=$(git log -1 --pretty=format:"%ae")
          COMMIT_HASH=$(git log -1 --pretty=format:"%H")
          JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Membangun payload menggunakan printf
          TEXT=$(printf "Branch(Version): %s\nLast Message: %s\nAuthor: %s\nCommit: %s\nJob URL: %s" "$BRANCH" "$LAST_COMMIT" "$AUTHOR" "$COMMIT_HASH" "$JOB_URL")

          # Panggil API menggunakan curl dengan multipart/form-data
          curl -X POST $API_URL \
            -H "x-api-secret: $API_SECRET" \
            -H "x-api-key: $API_KEY" \
            -F "text=$TEXT" \
            -F "number=$NUMBER_NOTIFICATION"

      # Login ke DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dante-proxy:latest .

      # Push Docker image ke DockerHub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dante-proxy:latest

